aips/higher-order-functions.md
In this AIP, we suggest a set of conventions to add higher-order inline functions to collection types as they appear in the Move and Aptos frameworks.
Discussion issue #33
=> [AIP] Higher-Order Inline Functions for Collections

TEMPLATE.md, aips/aip-1.md, aips/aip-2.md, aips/aip-3.md, aips/aip-4.md, aips/aip-6.md, aips/aip-7.md, aips/higher-order-functions.md, aips/objects.md, aips/resource_groups.md, aips/token_objects.md
This PR ensures that all AIPs have the AIP number and title as the first section header. This makes it much easier to immediately identify which AIP you're looking at. It also adds the title requirements to the template and fixes a small typo where AIP-7 was marked as 8 in the doc.
=> [AIPs] Ensure each AIP has the title as the first section header.

aips/aip-11-Move Objects.md
Removing a statement about `any` which isn't true (or misunderstandable?), as long as `any` is used in a linear timeline of compatible upgrades in a given network. Otherwise looks great!
=> [aip-11] Minimal edits

README.md, aips/aip-14.md, aips/new-hash-functions-and-multi-ed25519-natives.md
Also, updates `README.md` with instructions on how to submit an AIP.
Discussion will be held in this issue: https://github.com/aptos-foundation/AIPs/issues/57
=> AIP draft: New cryptography natives for hashing and MultiEd25519 PK validation

aips/new-hash-functions-and-multi-ed25519-natives.md
Updated timeline for https://github.com/aptos-foundation/AIPs/pull/59, as advised by @movekevin.
Tagging @michelle-aptos, @sherry-x and @davidiw for review (since I seem unable to manually add reviewers)
=> update timeline in AIP

TEMPLATE.md
As far as I can tell, the text in the template is asking about a **deployment** timeline on devnet, testnet and mainnet, not an _implementation_ timeline.
If it's asking about both things, let's add separate sections.
If it's asking about implementation, then I think the guidelines are confusing: i.e., what does deployment on devnet, testnet and mainnet have to do with the _implementation_ timeline?
=> replace 'implementation' with 'deployment'

aips/aip-10.md
Fixes typo at AIP-10 under the `LinearTransferRef`
=> fix: typo at LinearTransferRef aip10

aips/aip-41.md, aips/move-randomness.md
AIP discussion should take place here: https://github.com/aptos-foundation/AIPs/issues/185
=> [AIP] Move module for randomness generation

aips/aip-40.md
`10000` in binary is 16, not 15. Probably just an English slip up, I assume I used to say "up to 15" or something.
=> Fix binary -> decimal conversion in AIP 40

aips/aip-40.md
The AIP is already marked as accepted based on the labels in the repo, this just updates the file.
=> Mark AIP-40 as accepted in the file itself

TEMPLATE.md
I propose leaving the questions in the "quote box" so that AIP writers can provide the answer directly below them, as opposed to removing the questions and providing an answer without context. 
The additional context of the question being answered should be more helpful for the reader to understand.
It's also a good way for the AIP writer to ensure they are **actually answering** the **full** question!
=> Update TEMPLATE.md to put the question prompts in a quote box

aips/aip-41.md
- Added protection against _test-and-abort_ attacks
- Further simplified API by removing the `RandomNumberGenerator` struct.
- Discussed linter-based checks and callstack-based checks for improper uses of the `randomness` APIs.
=> Update AIP-41 to v1.2

aips/aip-56.md, aips/aip-resource-access.md
This contains a draft AIP for extending the Move language by resource access control.
Related PR: https://github.com/aptos-labs/aptos-core/pull/10480
Markdown view: https://github.com/aptos-foundation/AIPs/blob/wg-rw/aips/aip-56.md
=> [AIP Resource Access Control] Initial document

aips/aip-62.md
Adds a Error standard to the wallet standard following https://github.com/aptos-labs/wallet-standard/pull/2
=> Add errors standard to the wallet standard

aips/aip-61.md
=> AIP-61 updates

aips/aip-8.md
Clarify that Move does not have actual higher-order functions and dynamic dispatch.
=> Update aip-8 to clarify the absence of higher order functions

aips/aip-41.md
Some randomness hackathon participants were using AIP-41 as if the generated randomness were **secret** (i.e., as if it were known only to the transaction sender).
This PR clarifies the distinction between secret and public randomness.
=> AIP-41: Clarify public versus secret randomness

aips/aip-61.md
+ fraud detection on the MPC side
+ https://ethereum-magicians.org/t/eip-7522-oidc-zk-verifier-for-aa-account/15862
+ https://forum.openzeppelin.com/t/sign-in-with-google-to-your-identity-contract-for-fun-and-profit/1631
=> AIP-61 updates to zkSNARK relation, recovery service, code samples, training wheels, non-malleability, etc.

aips/aip-79.md
There's no way to do it correctly at the moment...
=> AIP-79 update: disable undergasing prevention

aips/aip-x-safe-auth-key-mapping.md
Add an AIP for safe onchain key rotation address mapping for standard accounts
=> Add AIP for safe onchain key rotation address mapping for standard accounts

aips/account_abstraction.md, aips/aip-104.md
AIP for account abstraction on Aptos
=> [AIP] Account Abstraction

aips/aip-61.md
- Oops, the description of the `override_aud` path was off in one place.
- Minor editorial change to the `idc_aud_val` description in the leaky mode
=> Fix override_aud description in Keyless AIP-61

aips/aip-96.md
- Added discussion on why recovery service mode for Federated Keyless would be trickier.
=> Discuss recovery service for Federated Keyless

aips/aip-114.md
Discussed, no feature flag needed, just use framework deployment to reduce governance overhead.
=> Update AIP 114 to remove featureflag

aips/aip-115.md, aips/aip-x.md
stateless account aip for orderless txn.
=> [AIP-x] stateless account update

aips/aip-117.md, aips/object-code-deployment-auth-ref.md
Adds AIP proposal for enabling signer capability support in object code deployment. This AIP outlines a solution to enable modules published under objects to access their object signer during initialization and store it for later use, similar to how modules published under resource accounts can retrieve and store their SignerCapability.
=> aip: add signer capability support for object code deployment

aips/aip-129.md, aips/aip-extra-config.md
This AIP changes the structure of a user transaction to support the upcoming orderless transactions feature. To support the orderless transaction feature, we had to add some extra information inside a user transaction. This AIP creates a way to add extra information info inside a user transaction.
Each transaction contains a `TransactionPayload` which could be either an entry function, script, or multisig. In this AIP, we add a new variant of `TransactionPayload` that can store both an executable (such as entry function, script), and some extra information.
=> Add extra config in transaction payload
