README.md

This PR updates the README to provide a simple AIP overview table, mapping the AIP number to the AIP title. This makes it much easier to navigate the AIPs and find what you're looking for 😄

[README] Update README to provide a simple AIP overview.

---

aips/aip-15.md

Update and rename token_standard_reserved_properties.md to aip-15.md

---

aips/aip-10.md

* ObjectId -> Object<T>
* Refined APIs
* Lots of comments
* Tried to cut down on verbosity

move objects update

---

aips/aip-18.md

[AIP-18] Introducing SmartVector and SmartTable

---

aips/aip-27.md

Add AIP for sender aware transaction shuffling

AIP for sender aware transaction shuffling

---

aips/aip-21.md

- change `allow_ungated_balance_transfer` to `frozen`.
- change `set_ungated_transfer` to `set_frozen_flag`.
match https://github.com/aptos-labs/aptos-core/pull/7908

[aip-21] update api name

---

aips/aip-xx.md

This PR adds a draft AIP for the peer monitoring service.

[AIP] Add AIP draft for the peer monitoring service.

---

aips/aip-29.md

This PR makes several small tweaks to the AIP for the peer monitoring service:
- Update the AIP type to "Informational".
- Add the missing "Risks and Drawbacks" section.
- Refine the suggested implementation timeline.
- Add a small "Stakeholder Impact" section.

[AIP 29] Small tweaks and extensions to peer monitoring service.

---

aips/aip-35.md

Fix grammar issues in aip-35.md

---

aips/address-standard-v1.md

This PR introduces an AIP for Address Standard v1. See more in the AIP.

Add Address Standard v1 AIP

---

aips/aip-40.md

Adding more information to the ecosystem impact, as discussed offline.

[AIP-40] Add ecosystem impact / timeline

---

README.md

Make it clearer what an AIP is.

Make it clearer what an AIP is.

---

README.md
aips/aip-41.md

Filled everything in so AIP can be discussed publicly.

Updates to AIP-41

---

aips/aip-41.md

Oops, didn't have a chance to incorporate some edits.

edits to AIP-41

---

aips/aip-30.md

- Fixed the latex expression display issue
- Added another line of example (e.g., 51th year)
- Updated the timeline to Q3 2023

Updated the AIP-30

---

aips/aip-41.md

Formatting, typos and simplifying the default API.

AIP-41: New Rust-like RNG API

---

aips/aip-41.md

Typo in aip-41.md

---

aips/aip-32.md

1. refund to the deleter.
2. always full refund without declining ratio
3. remove the global deposit for now for simplicity and performance.

Update aip-32.md: full refund, to the deleter

---

aips/aip-43.md

last pass for updating AIP-43 , for the community review phase

Update aip-43.md into "In Review"

---

aips/aip-47.md

AggregatorV2 ready for community feedback

AggregatorV2 AIP changes to be ready for community feedback

---

aips/aip-40.md

I link to a specific commit rather than main so the line numbers in the URL stay correct.

[AIP-40] Update git hash used for reference implementation

---

aips/aip-41.md

AIP-41: Fix function visibility in Move example

---

README.md

Update README.md: fix link to AIP-38 discussion

---

aips/aip-43.md

Update aip-43 - concurrent token v2 and fungible assets - for v1.10 plans and more indexer details

---

aips/aip-41.md

Discussing undergasing attacks & their defenses.

Undergasing attacks in AIP-41

---

aips/aip-54.md

Update description AIP-54 Object Code Deployment with
- Reference implementation
- Updates to code description, referencing from the PR: https://github.com/aptos-labs/aptos-core/pull/11748

Update description AIP-54 Object Code Deployment

---

aips/aip-67.md

Calling out the assumptions of when JWK consensus will work and examples of when it will not.

aip 67 update

---

aips/aip-43.md

since we are deploying them in separate releases, having consequences and impact explained together was confusing I think.

Move fungible asset changes out of AIP-43 into a separate AIP

---

aips/aip-67.md

HTTP oracles! Need I say more?

Future potential of AIP-67

---

aips/aip-63.md

revise aip63

---

TEMPLATE.md

This PR updates the AIP template for the paragraphs:
- Risks and Drawbacks
- Security Considerations

Update Security considerations in TEMPLATE.md

---

aips/aip-71.md
aips/aip-X.md

per request.
Let's make an AIP for this.

[AIP-X] Migrate Aptos Framework Events to Module Events

---

aips/aip-72.md
aips/aip-x.md

AIP which creates a standard for minting digital assets on the Aptos Blockchain

Minting Standard for Digital Assets AIP

---

aips/aip-74.md

AIP-74 - Increase block gas limit to account for concurrency increase

AIP-74 - Increase block gas limit to account for concurrency increase

---

aips/aip-63.md

[aip63] revise

---

aips/aip-61.md

Fix typo aip-61.md

---

aips/aip-78.md

Update Aptos Token Objects Framework Update to AIP 78

Update to AIP 78

---

aips/aip-80/aip-80.md
aips/aip-standardize-private-keys.md

This is a proposal for a standard on private keys that differentiates them from other identifiers to prevent mistakes

Proposal for standardizing private keys

---

aips/aip-78.md

Add reference implementation to AIP 78

Add reference implementation to AIP 78

---

aips/aip-41.md
aips/aip-79.md

- API should be discussed in a separate AIP (AIP-41?)
- updated on-chain conig refactoring specifications

api and on-chain config updates for randomness

---

aips/aip-82.md
aips/aip-83.md

framework-level untransferable fungible asset stores

---

aips/gas-coverage-improvements.md

This adds the AIP for the new gas charges and limits introduced recently.
Note: this is a retrospective proposal reflecting on a security feature that has already been implemented due to it being a security fix.

Retrospective AIP: improving gas coverage

---

aips/bn254.md

Discussion [here](https://github.com/aptos-foundation/AIPs/issues/437).

BN254 Move module

---

aips/aip-62.md

Update `signAndSubmitTransaction` AIP-62 standard function following users feedback

Update `signAndSubmitTransaction` AIP-62 standard function

---

aips/aip-89.md
aips/aip-order-votes.md

Adding a new AIP for order votes

Create AIP for order votes

---

aips/aip-62.md

Fix typo in AIP-62

---

aips/aip-93.md

This PR adds a draft AIP for consensus observer.

[AIP] Add draft AIP for consensus observer.

---

aips/aip-75.md

Add liveness risk to AIP-75

---

aips/aip-99.md
aips/aip-x-disable-object-burn.md

This AIP proposes to disable safe burn of user owned objects.

[draft] AIP-X Disable safe burn of user owned objects

---

aips/aip-107.md
aips/new-loader-and-code-cache-for-move-vm.md

See the description file of the AIP for more details.

[AIP-X] New Loader and Code Cache for Move VM

---

aips/aip-81.md

... to reflect the latest pepper service change.
Summary:
- Remove pepper encryption.
- Add derived pepper.

AIP-81 update

---

aips/aip-112.md
aips/aip-function-values.md

AIP proposal for function values.

[AIP Proposal] Function Values in the Move VM

---

aips/aip-49.md

Typos in aip-49.md

---

aips/aip-114.md

Updates with indexer changes that change column width to 32 bytes

[aip-114] Update to include indexer changes

---

aips/aip-112.md

Considers early feedback from auditors and refines aspects resulting from implementation.
Preview: https://github.com/aptos-foundation/AIPs/blob/590abcd2658885ffe054e5d656e3ae8759c43ff4/aips/aip-112.md

[aip-112] Update Function Value AIP

---

aips/aip-56.md

Updates AIP to latest version aligning with implementation.

[AIP-56] Update to v2

---

aips/aip-56.md

Updates aip-56 with a more extensive motivation section.
Preview: https://github.com/aptos-foundation/AIPs/blob/wrwg/aip-56-v3/aips/aip-56.md

[resource access control] Flesh out motivation section

---

aips/aip-127.md

Updating AIP based on the most recent changes. Fixing grammar issues.

[lazy-loading] Update AIP
